version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ironsaas_cashflow
      POSTGRES_USER: ironsaas
      POSTGRES_PASSWORD: ironsaas
    ports:
      - '5436:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
